version: '3.8'

services:
  db:
    image: postgres:13
    restart: always
    container_name: postgres-db
    ports:
      - 5433:5432
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_DB: event_manager
      POSTGRES_USER: inno
      POSTGRES_PASSWORD: inno