spring:
  # Настройка liquibase миграций
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
  # Hibernate & JPA
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
  # Настройка подключения к базе
  datasource:
    #driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/event_manager?serverTimezone=Europe/Moscow
    username: inno
    password: inno
  freemarker:
    expose-request-attributes: true
  mail:
    host: smtp.yandex.ru
    username: dk-st31-eventmanager@yandex.ru
    #password: eventmanager
    password: zmlquqcwfwqjymod
    port: 465
    protocol: smtps
  session:
    jdbc:
      initialize-schema: always
      table-name: SPRING_SESSION
mail:
  debug: true
logging:
  level:
    liquibase: INFO
    org:
      hibernate:
        type: TRACE
#    org.springframework.web: TRACE
