<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom shadow-sm">
    <h5 class="my-0 mr-md-auto font-weight-normal">Супер крутой - стартап 2020!</h5>
<#--    <nav class="my-2 my-md-0 mr-md-3">-->
    <nav>
        <a href="/">Главная страница</a>
        <a href="/list">Cписок</a>
        <a href="/registration">Регистрация</a>
        <a href="/login">Войти</a>
    </nav>
<#--    <a class="btn" href="#">Что - то сделать!</a>-->
</div>